# Program pertama CLAW
print("=" * 50)
print("SELAMAT DATANG DI CLAW")
print("Coordinator's Local Assistant Worker")
print("=" * 50)
print()
nama = input("Siapa nama Anda? ")
print()
print(f"Halo {nama}! Saya CLAW, asisten pribadi Anda.")
print("Saya akan membantu pekerjaan di Kementerian ATR/BPN.")
print()
print("Fitur yang akan saya miliki:")
print("  📅 Jadwal & Reminder")
print("  📝 Catatan Cepat")
print("  📊 Template Dokumen")
print("  ⏰ Proactive Assistant")